apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-backend:c6c2a7613f2712b63588882ade965601b357b821
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: react-config
            - secretRef:
                name: db-secret

